Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
list = ['1','2','3','4','5']
type(list)

list

In [5]:
import numpy as np
array_list = np.array(object = list)
type(array_list)

numpy.ndarray

so,here ndarray stores only same size and type of data whereas list stores every type of data.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [8]:
list = ['1','2','3','4','5']
type(list[0])
#as the all elements are in form of '' so ithe all elements are str in list. 

str

In [15]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1.dtype

dtype('int64')

Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.


In [53]:
list = ['1','2','3','4','5']
type(list)

list

In [52]:
import numpy as np
array_list = np.array(object = list)
type(array_list)

numpy.ndarray

so,here the difference is that the list stores all type of data whereas ndarray is an array name in python that stores the same type of data and size. 

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [18]:
import numpy as np
num_list = [[1,2,3] , [4,5,6]]
num_array = np.array(list) #in a list form
num_array.shape

(5,)

In [19]:
num_list = [[1,2,3] , [4,5,6]]
num_array = np.array(list)
num_array.size

5

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [21]:
import numpy as np
arr = np.array(object = list)
np.zeros((3,3,(3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
import numpy.matlib as nm
nm.zeros(9)

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])